ALTER TABLE ARTICOLCOMANDA DROP CONSTRAINT FK_ARTICOLCOMANDA_COMANDA_ID
ALTER TABLE ARTICOLCOMANDA DROP CONSTRAINT FK_ARTICOLCOMANDA_PRODUS_COD
ALTER TABLE COMANDA DROP CONSTRAINT FK_COMANDA_CLIENT_ID
ALTER TABLE FURNIZOR_PRODUS DROP CONSTRAINT FK_FURNIZOR_PRODUS_produse_COD
ALTER TABLE FURNIZOR_PRODUS DROP CONSTRAINT FK_FURNIZOR_PRODUS_Furnizor_COD
ALTER TABLE TIPFUNIZOR_FURNIZOR DROP CONSTRAINT FK_TIPFUNIZOR_FURNIZOR_TipFunizor_IDTIPF
ALTER TABLE TIPFUNIZOR_FURNIZOR DROP CONSTRAINT FK_TIPFUNIZOR_FURNIZOR_funizori_COD
DROP TABLE ARTICOLCOMANDA CASCADE
DROP TABLE CLIENT CASCADE
DROP TABLE COMANDA CASCADE
DROP TABLE FURNIZOR CASCADE
DROP TABLE PRODUS CASCADE
DROP TABLE TIPFUNIZOR CASCADE
DROP TABLE FURNIZOR_PRODUS CASCADE
DROP TABLE TIPFUNIZOR_FURNIZOR CASCADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
